# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('category_image', models.ImageField(null=True, upload_to='/static/category_images')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=400, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('product_image', models.ImageField(null=True, upload_to='/static/product_images')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_Steel_kiwi.Category')),
            ],
            options={
                'db_table': 'products',
            },
        ),

    ]
