# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 13:12
from __future__ import unicode_literals

from django.db import migrations
from project_utils.utils import slug_creator
from django.contrib.auth.hashers import make_password
from django.utils.text import slugify
import mimesis
import random


def creating_category(apps, schema_editor):
    category = apps.get_model("task_Steel_kiwi", "Category")
    products = apps.get_model("task_Steel_kiwi", "Product")
    user = apps.get_registered_model("auth", "User")
    hardware = mimesis.Hardware()
    text = mimesis.Text()
    for _ in range(5):
        randomize_hardware = random.choice([hardware.cpu(), hardware.graphics()])
        category.objects.create(name=randomize_hardware,
                                description=text.text(quantity=3),
                                slug=slug_creator(name=randomize_hardware), )

    for _ in range(30):
        randomize_hardware = random.choice([hardware.cpu(), hardware.graphics()])
        category_n = category.objects.order_by('?').first()
        products.objects.create(
            category=category_n,
            name=randomize_hardware,
            description=text.text(quantity=3),
            price=round(random.uniform(10.00, 1000.00), 2),
            slug=slug_creator(name=randomize_hardware),
        )
    user.objects.create(
        username='admin',
        password=make_password('adminadmin'),
        is_staff=True,
        is_superuser=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('task_Steel_kiwi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(creating_category),
    ]
